name: Commit CI

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    tags:
      - '[0-9]+.*'
    paths:
      - '**/**'
      - '!*.md'
      - '!.gitignore'
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout last commit
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Ninja
        run: |
          $ErrorActionPreference = 'Stop'
          choco install ninja

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build rimeac.lua
        run: |
          $ErrorActionPreference = 'Stop'
          .\deps.install.bat
          .\build_vc.bat

      - name: Compress dists
        run: |
          $ErrorActionPreference = 'Stop'
          del dist\.placeholder
          del dist64\.placeholder
          move dist rimeac.lua.x86
          move dist64 rimeac.lua.x64
          7z.exe a -t7z rimeac.lua.x86.7z rimeac.lua.x86\*
          7z.exe a -t7z rimeac.lua.x64.7z rimeac.lua.x64\*

      # create nightly release
      - name: Create Nightly release
        uses: 'marvinpinto/action-automatic-releases@latest'
        if: ${{ github.repository == 'fxliang/rimeac.lua' && github.ref == 'refs/heads/master' }}
        with:
          repo_token: ${{ secrets.WORKFLOW_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: "Nightly Build"
          files: |
            ./rimeac.lua.x86.7z
            ./rimeac.lua.x64.7z

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        with:
          files: |
            ./rimeac.lua.x86.7z
            ./rimeac.lua.x64.7z

